name: Seekers-Dream CI Workflow

on:
  push:
    branches:
      - dev # Trigger workflow only on the dev branch
  pull_request:
    branches:
      - dev

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint-and-test:
    name: Lint, Format Check, and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Step 1: Checkout Code
      - uses: actions/checkout@v4

      # Step 2: Use Node.js version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm ci # Ensures clean installs of dependencies for consistency

      # Step 4: Linting (TypeScript Linter)
      - name: Run ESLint
        run: npx eslint './**/*.ts' './**/*.tsx' --fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Formatting Check
      - name: Run Prettier Check
        run: npx prettier --check './**/*.{ts,tsx,json,md}'

      # Step 6: Run TypeScript Compiler
      - name: TypeScript Strict Compilation
        run: npx tsc --noEmit --strict

      # Step 7: Run Tests
      - name: Run Tests
        run: npm test -- --coverage # Include test coverage report
