name: 'Seekers-Dream Lint'

on:
  push:
    branches:
      - dev # Trigger workflow only on the dev branch
  pull_request:
    branches:
      - dev

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint-and-test:
    name: Lint, Format Check, and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: npm ci # Ensures clean installs of dependencies for consistency

      # Step 3: Linting (TypeScript Linter)
      - name: Run ESLint
        run: npx eslint './**/*.ts' './**/*.tsx' --fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Formatting Check
      - name: Run Prettier Check
        run: npx prettier --check './**/*.{ts,tsx,json,md}'

      # Step 5: Run TypeScript Compiler
      - name: TypeScript Strict Compilation
        run: npx tsc --noEmit --strict

      # Step 6: Run Tests
      - name: Run Tests
        run: npm test -- --coverage # Include test coverage report
