name: Seekers-Dream CI Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  lint-and-test:
    name: Lint, Format Check, and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Test only on Node.js 18.x for now

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Linters
        run: npx eslint './**/*.ts' './**/*.tsx' --fix

      - name: Run Prettier Check
        run: npx prettier --check './**/*.{ts,tsx,json,md}'

      - name: Run TypeScript Compilation
        run: npx tsc --noEmit --strict

      - name: Run Tests
        run: npm test -- --coverage
