name: Seekers-Dream CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Lint, Format Check, and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Test only on Node.js 18.x for now

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Run Linters
        run: npx eslint './**/*.ts' './**/*.tsx' --fix

      - name: Run Prettier Check
        run: npx prettier --check 'src/**/*.{ts,tsx,json,md}'

      - name: Build
        run: npm run build

      - name: Run TypeScript Compilation
        run: npx tsc --noEmit --strict

        # - name: Run Tests
        #   run: npm test -- --coverage
